const ActionTypes = {
  INSTALLING_MAP: 'INSTALLING_MAP',
  INSTALLED_MAP: 'INSTALLED_MAP',
  RECEIVE_DEVICES: 'RECEIVE_DEVICES',
  RECEIVE_MAPS: 'RECEIVE_MAPS',
  SELECT_DEVICE: 'SELECT_DEVICE',
  SELECT_STYLE: 'SELECT_STYLE'
}

module.exports = ActionTypes
